# Generated by Django 5.1.2 on 2024-11-20 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTrabajoUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('area_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_area_trabajo', to='empresas.areatrabajo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_trabajo_usuario', to='usuarios.usuarios')),
            ],
            options={
                'unique_together': {('usuario', 'area_trabajo', 'empresa')},
            },
        ),
    ]
