# Generated by Django 5.1.2 on 2024-11-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_remove_areatrabajo_responsable_del_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
