# Generated by Django 5.1.2 on 2024-12-03 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresa_activo'),
        ('empresas', '0005_empresa_empleado'),
    ]

    operations = [
    ]
