# Generated by Django 5.1.2 on 2024-12-03 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_merge_0005_empresa_activo_0005_empresa_empleado'),
        ('usuarios', '0006_alter_usuarios_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='empleado',
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_trabajador', to='empresas.empresa')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajador_empresa', to='usuarios.usuarios')),
            ],
        ),
    ]
