# Generated by Django 5.1.2 on 2024-12-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_remove_empresa_empleado_empleados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatrabajo',
            name='nombre_area',
            field=models.CharField(choices=[('marketing', 'MARKETING'), ('ti', 'TI'), ('atencion_cliente', 'ATENCION_CLIENTE'), ('recursos_humanos', 'RECURSOS_HUMANOS'), ('finanzas', 'FINANZAS')], max_length=30),
        ),
    ]
