# Generated by Django 5.1.2 on 2024-12-04 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_alter_areatrabajo_nombre_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='areatrabajousuarios',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
            preserve_default=False,
        ),
    ]
