# Generated by Django 5.1.2 on 2024-12-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_areatrabajousuarios_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatrabajo',
            name='nombre_area',
            field=models.CharField(choices=[('Marketing', 'MARKETING'), ('TI', 'TI'), ('Atencion al cliente', 'ATENCION_CLIENTE'), ('Recursos humanos', 'RECURSOS_HUMANOS'), ('Finanzas', 'FINANZAS')], max_length=30),
        ),
    ]
