# Generated by Django 5.1.2 on 2024-11-18 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_encuesta', models.CharField(max_length=200)),
                ('descripcion_encuesta', models.TextField()),
                ('fecha_creacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_texto', models.TextField()),
                ('encuesta_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.encuestas')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_referencia', models.IntegerField()),
                ('respuesta_texto', models.TextField()),
                ('fecha_respuesta', models.DateField(auto_now=True)),
                ('encuesta_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.encuestas')),
                ('pregunta_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.pregunta')),
            ],
        ),
    ]
