# Generated by Django 5.1.2 on 2024-11-24 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
        ('usuarios', '0002_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='usuario_referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_responde', to='usuarios.usuarios'),
        ),
    ]
