# Generated by Django 5.1.2 on 2024-11-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_alter_respuesta_usuario_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='respuesta_texto',
            field=models.CharField(choices=[('MUY BUENA', 'Muy buena'), ('BUENA', 'Buena'), ('REGULAR', 'Regular'), ('MALA', 'Mala'), ('MUY MALA', 'Muy mala')], max_length=11),
        ),
    ]
