# Generated by Django 5.1.2 on 2024-11-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_alter_respuesta_respuesta_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='retroalimentacion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
