# Generated by Django 5.1.2 on 2024-12-05 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_alter_areatrabajo_nombre_area'),
        ('encuestas', '0005_alter_respuesta_retroalimentacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuestas',
            name='titulo_encuesta',
        ),
        migrations.AddField(
            model_name='encuestas',
            name='categoria_encuesta',
            field=models.CharField(choices=[('Salud Mental', 'Salud Mental'), ('Ambiente Laboral', 'Ambiente Laboral'), ('Equilibrio Vida-Trabajo', 'Equilibrio Vida-Trabajo'), ('Beneficios y Compensaciones', 'Beneficios y Compensaciones'), ('Comunicación Interna', 'Comunicación Interna'), ('Oportunidades de Crecimiento', 'Oportunidades de Crecimiento')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuestas',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_empresa', to='empresas.empresa'),
            preserve_default=False,
        ),
    ]
