# Generated by Django 5.1.2 on 2024-12-05 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_alter_areatrabajo_nombre_area'),
        ('encuestas', '0006_remove_encuestas_titulo_encuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_empresa', to='empresas.empresa'),
            preserve_default=False,
        ),
    ]
