# Generated by Django 5.1.2 on 2024-12-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0007_respuesta_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestas',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
