# Generated by Django 5.1.2 on 2024-12-20 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0008_encuestas_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='retroalimentacion',
        ),
    ]
