# Generated by Django 5.1.2 on 2024-12-02 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_remove_areatrabajo_responsable_del_area_and_more'),
        ('usuarios', '0002_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioEmpresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
