# Generated by Django 5.1.2 on 2024-12-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuarioempresas_delete_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioempresas',
            name='rol',
            field=models.CharField(choices=[('usuario', 'USUARIO'), ('trabajador', 'TRABAJADOR'), ('propietario', 'PROPIETARIO'), ('recursos_humanos', 'RECURSOS_HUMANOS')], default='usuario', max_length=30),
        ),
    ]
