# Generated by Django 5.1.2 on 2024-12-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuarios_rol_delete_usuarioempresas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(choices=[('usuario', 'USUARIO'), ('propietario', 'PROPIETARIO'), ('trabajador', 'TRABAJADOR'), ('recursos_humanos', 'RECURSOS_HUMANOS')], default='usuario', max_length=30),
        ),
    ]
