# Generated by Django 5.1.2 on 2024-12-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuarios_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='imagen_perfil',
            field=models.TextField(default='https://static-00.iconduck.com/assets.00/profile-circle-icon-512x512-zxne30hp.png'),
        ),
    ]
