# Generated by Django 5.1.2 on 2024-12-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuarios_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='imagen_perfil',
            field=models.TextField(blank=True, default='https://static-00.iconduck.com/assets.00/profile-circle-icon-512x512-zxne30hp.png', null=True),
        ),
    ]
