# Generated by Django 5.1.2 on 2024-12-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_usuarios_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cedula_usuario',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
